---
name: ZI Code Documentation
on: 
  workflow_dispatch:
  schedule:
  - cron: "30 4 * * 4"

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Install zsdoc
        run: |
          sudo apt-get install -y zsh
          git clone https://github.com/z-shell/zsdoc.git /tmp/zsdoc
          sudo make -C /tmp/zsdoc install
      - name: ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: asciidoctor-pdf
        run: |
          gem install asciidoctor-pdf
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Clone repository
        run: |
          git clone https://github.com/z-shell/zi.git zi
      - name: Parse scripts and generate Asciidoc documents
        run: |
          make -C zi/docs doc
      - name: Generate PDF from Asciidoc documents
        run: |
          make -C zi/docs/zsdoc pdf
          mv -vf zi/docs/zsdoc/*.adoc docs/code/asciidoc/
          mv -vf zi/docs/zsdoc/pdf/*.pdf docs/code/pdf/
          echo "$(git log --relative-date)" > docs/COMMITLOG.md
      - name: Tar Code documentation
        run: |
          tar cvzf code-documentation.tar.gz docs/code
      - name: Upload docs.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: Upload Code documentation artifact
          path: |
            code-documentation.tar.gz
      - name: Check if update required for zsdoc 
        run: |
          git --no-pager diff docs/code 
          if git --no-pager diff --quiet docs/code
          then
            echo "The Code Doocumentation are up to date"
          else
            {
              echo "The Code Doocumentation in the repo are not up to date"
              echo 'Please regenerate them with $ make doc'
            } >&2
            exit 1
          fi
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Code Documentation Update"
          branch: main
          # See https://git-scm.com/docs/git-commit#_options
          commit_options: '--no-verify --signoff'
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: docs
          repository: .
          commit_user_name: Z-Shell Bot
          commit_user_email: z-shell@digitalclouds.dev
          commit_author: Z-Shell ZI <z-shell@digitalclouds.dev>
          #tagging_message: 'v1.0.0'
          # See https://git-scm.com/docs/git-status#_options
          status_options: '--untracked-files=no'
          # See https://git-scm.com/docs/git-add#_options
          #add_options: '-u'
          push_options: '--force'
          skip_dirty_check: true
          skip_fetch: true
          # Details: https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html
          disable_globbing: true
